/* Generated By:JavaCC: Do not edit this line. expConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface expConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Letra = 1;
  /** RegularExpression Id. */
  int Numero = 2;
  /** RegularExpression Id. */
  int Decimal = 3;
  /** RegularExpression Id. */
  int Oceano = 4;
  /** RegularExpression Id. */
  int Anio_reg = 5;
  /** RegularExpression Id. */
  int Nombre = 10;
  /** RegularExpression Id. */
  int Numero_registros = 11;
  /** RegularExpression Id. */
  int Numero_ciclon = 12;
  /** RegularExpression Id. */
  int Anio = 13;
  /** RegularExpression Id. */
  int Hora_reg = 16;
  /** RegularExpression Id. */
  int Identificador_registro = 17;
  /** RegularExpression Id. */
  int Estado = 18;
  /** RegularExpression Id. */
  int Latitud = 19;
  /** RegularExpression Id. */
  int Longitud = 20;
  /** RegularExpression Id. */
  int Mes_reg = 21;
  /** RegularExpression Id. */
  int Dia_reg = 22;
  /** RegularExpression Id. */
  int Minutos_reg = 23;
  /** RegularExpression Id. */
  int Vientos_max = 26;
  /** RegularExpression Id. */
  int Pres_min = 29;
  /** RegularExpression Id. */
  int Meta = 32;
  /** RegularExpression Id. */
  int Retornar = 33;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int CABECERA = 1;
  /** Lexical state. */
  int PT_NCICLON = 2;
  /** Lexical state. */
  int PT_ANIO = 3;
  /** Lexical state. */
  int REGISTROS = 4;
  /** Lexical state. */
  int PT_MES = 5;
  /** Lexical state. */
  int PT_DIA = 6;
  /** Lexical state. */
  int PT_MINUT = 7;
  /** Lexical state. */
  int PT_VMAX = 8;
  /** Lexical state. */
  int PT_PMIN = 9;
  /** Lexical state. */
  int PT_META = 10;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Letra>",
    "<Numero>",
    "<Decimal>",
    "<Oceano>",
    "<Anio_reg>",
    "\" \"",
    "\",\"",
    "\"\\n\"",
    "\"\\r\"",
    "<Nombre>",
    "<Numero_registros>",
    "<Numero_ciclon>",
    "<Anio>",
    "\" \"",
    "\",\"",
    "<Hora_reg>",
    "<Identificador_registro>",
    "<Estado>",
    "<Latitud>",
    "<Longitud>",
    "<Mes_reg>",
    "<Dia_reg>",
    "<Minutos_reg>",
    "\" \"",
    "\",\"",
    "<Vientos_max>",
    "\" \"",
    "\",\"",
    "<Pres_min>",
    "\" \"",
    "\",\"",
    "<Meta>",
    "\"\\n\"",
    "\" \"",
    "\",\"",
    "\"\\r\"",
  };

}
